version: "3"

services:
  tiktok:
    image: tiktok-discord-bot_tiktok
    build: .
    container_name: TikTokDownloaderBot
    environment:
      - token=${token}
    ports:
      - 10080:80
      - 18080:8080
    restart: unless-stopped
